### ISSUE TITLE
Alternative links for checkpoints

### ISSUE THREAD

**Issue by algvr** [linfeng93/Large-UniDet#1]
Dear authors, thank you for the amazing work!

Would it be possible to provide mirrors for the checkpoints, hosted e.g. on Google Drive? The current link is slow and difficult to use in Europe.

Thank you very much in advance!

**Comment by linfeng93** [comment]
@algvr 
Thank you for your interest in our work.
As per your request, we have made a copy of the checkpoints on [Google Drive](https://drive.google.com/drive/folders/1NOUlR0oQbyzeTfW3RnjvpAQ7tWFHyyp0?usp=sharing).
hope everything goes well

**Comment by algvr** [comment]
Thanks a lot!
